[package]
name = "mleap-bundle"
version = "0.1.0"
authors = ["Hollin Wilkins <hollinrwilkins@gmail.com>"]

[dependencies]
clippy = {version = "*", optional = true}
uuid = "0.4"
semver = "0.6.0"
zip = "0.2"
